### ISSUE TITLE
Please release 2.2

### ISSUE THREAD

**Issue by michaldo** [krzysztofslusarski/continuous-async-profiler#33]
Current version 2.1 does not have own tag and does not support `async-profiler.continuous.compression-interval`

**Comment by krzysztofslusarski** [comment]
From next release I want the version of this library to be tied up with default async-profiler version. I will release 2.9 soon. Do you want to push some more PRs into next release?

**Comment by michaldo** [comment]
No. Output file prefix, option to disable compression and 2.7.+ compatible autoconfiguration is good enough for now

**Comment by krzysztofslusarski** [comment]
2.9 released, should be in maven central by tomorrow
