### ISSUE TITLE
Colon ':' in file name is confusing

### ISSUE THREAD

**Issue by michaldo** [krzysztofslusarski/continuous-async-profiler#37]
https://github.com/krzysztofslusarski/continuous-async-profiler/blob/e70bd61e639969d13f7452f8899af708dfe3d241/continuous-async-profiler/src/main/java/com/github/krzysztofslusarski/asyncprofiler/ContinuousAsyncProfilerRunner.java#L33

I noticed few times colon can be confusing:

> kubectl cp /app/profiler-output/wall-2024-02-21_12:26:18.jfr  wall-2024-02-21_12:26:18.jfr
error: one of src or dest must be a local file specification

Windows Explorer
![image](https://github.com/krzysztofslusarski/continuous-async-profiler/assets/4304236/2dc23edd-7d7f-455b-ba9e-ca82ec4aa176)

Intellij
![image](https://github.com/krzysztofslusarski/continuous-async-profiler/assets/4304236/36b25b0c-3663-4172-91c1-84da54936a40)

My proposul is replace ':' by '_', huh?

**Comment by krzysztofslusarski** [comment]
Is this only an issue on Windows? The colon is a valid filename character and it's kind of standard way of using it in time. On linux you just need to escape it:
```
$ ls wall-2021-07-17_13\:05\:33.jfr.gz 
wall-2021-07-17_13:05:33.jfr.gz
```

If you need we can add the formatter pattern as a property so you could overwrite it, but I'm against changing the default.

**Comment by michaldo** [comment]
`kubectl` which rejects colon is installed on WSL, but fails also on Mac. Intellij screenshot is Windows

I agree colon is standard time separator but not necessary good choice for filename

**Comment by krzysztofslusarski** [comment]
Yeah, but I know that there are production systems that use this library and rely on that the filename has a colon. So it basically too late for changing it as default. 

Again, I'm ok with making it configurable.

**Comment by michaldo** [comment]
I prefer modify my kubectl script than implement configurable map and then propagate configuration to many microservices

Maybe 3.x will be opportunity to improve defaults
